### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by bclayton-usgs**
## nshmp-haz-ws is Dockerized
* New Dockerfile
* New .dockerignore file
* New docker.sh file for Docker to download repos
* New docker-compose.yaml file

The following information will be added to the wiki when this get approved.

### Run nshmp-haz-ws using Docker
```bash
docker run -p 8080:8080 -d nshmp/nshmp-haz-ws:latest
```

### Build and Run local image
```bash
# Build
docker build -t nshmp-haz-ws:latest .

# Run
docker run -p 8080:8080 -d nshmp-haz-ws:latest
```

### Docker build arguments
Docker image can be build with version, commit, or branch of the repositories it needs.
```bash
docker build \
--build-arg NSHMP_HAZ_VERSION=master \
--build-arg NSHM_AK_2007_VERSION=master \
--build-arg NSHM_COUS_2008_VERSION=master \
--build-arg NSHM_COUS_2014_VERSION=master \
--build-arg NSHM_COUS_2018_VERSION=master \
-t nshmp-haz-ws:latest .
```

### CODE REVIEW

**Review by pmpowers-usgs — CHANGES_REQUESTED** [review]
* Change java VM arg to -Xmx8g
* Add comment to readme and dockerfile a la: "Models load as requested. While all supported models are available, requesting them all will eventually result in an `OutOfMemoryError`. Increase `-Xmx` to `-Xmx16g` or `-Xmx24g`, if available"

**Comment by bclayton-usgs** [comment]
Added notes to Dockerfile. Will add info to wiki.

**Comment by bclayton-usgs** [comment]
The [wiki](https://github.com/usgs/nshmp-haz-ws/wiki/building-&-running) has been updated to show Docker info.

**Review by pmpowers-usgs — COMMENTED** [review]
good

**Pull request merged**
